library(shiny)
library(shinydashboard)
library(Rfacebook)
library(DT)
library(rCharts)
library(xml2)
library(httr)
require(tm)
library(cluster)
library(ape)
library(dplyr)
library(jiebaR)
library(wordcloud2)
source("function/PTT.R", encoding = "UTF-8")
source("function/CNA.R", encoding = "UTF-8")
source("function/ETTODAY.R", encoding = "UTF-8")
source("function/LTN.R", encoding = "UTF-8")
source("function/SETN.R", encoding = "UTF-8")
source("function/UDN.R", encoding = "UTF-8")